font=NotoSerif NF:size=18
line-height=32
fields=name,generic,exec,categories,keywords,filename
lines=8
icon-theme=WhiteSur-light
width=25
horizontal-pad=10
vertical-pad=10
prompt="   "
match-mode=fuzzy


[colors]
# dark
#bg: #1D2021;
#bg1: #3C3836;
#bg2: #504945;
#bg3: #665C54;
#bg4: #7C6F64;
#fg: #EBDBB2;
#fgMuted: #A89984;

# light
#bg: #F2E5BC;
#bg1: #EBDBB2;
#bg2: #D5C4A1;
#bg3: #BDAE93;
#bg4: #A89984;
#fg: #282828;
#fgMuted: #7C6F64;

#red: #FB4934;
#redMuted: #CC241D;
#blue: #83A598;
#blueMuted: #458588;
#purple: #D3869B;
#purpleMuted: #B16286;
#orange: #FE8019;
#orangeMuted: #D65D0E;
#aqua: #8EC07C;
#aquaMuted: #689D6A;
#yellow: #FABD2F;
#yellowMuted: #D79921;
#green: #B8BB26;
#greenMuted: #98971A;

border=282828ff
background=F2E5BCff
text=282828ff
match=CC241Dff
selection=7C6F64ff
selection-match=FB4934ff
selection-text=F2E5BCff
prompt=282828ff
input=282828ff

[border]
radius=2
width=1

[key-bindings]
execute=Return KP_Enter Control+m
execute-input=Shift+Return Shift+KP_Enter Control+Shift+m
