[config]
set = false # this prevents setting wallpaper with matugen

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel.ini'
output_path = '~/.config/fuzzel/colors.ini'

[templates.foot]
input_path = '~/.config/matugen/templates/foot.ini'
output_path = '~/.config/foot/colors.ini'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.astal]
input_path = '~/.config/matugen/templates/astal.scss'
output_path = '~/.config/astal-widgets/colors.scss'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-dark'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

# TODO: add neovim template

[config.custom_colors.red]
color = "#AF3029"
blend = true

[config.custom_colors.green]
color = "#66800B"
blend = true

[config.custom_colors.yellow]
color = "#AD8301"
blend = true

[config.custom_colors.blue]
color = "#205EA6"
blend = true

[config.custom_colors.magenta]
color = "#A02F6F"
blend = true

[config.custom_colors.cyan]
color = "#24837B"
blend = true

[config.custom_colors.white]
color = "#FFFCF0"
blend = true

[config.custom_colors.black]
color = "#100F0F"
blend = true
