[config]
set = false # this prevents setting wallpaper with matugen

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel.ini'
output_path = '~/.config/fuzzel/colors.ini'

# INFO: deactivated until fix of https://github.com/InioX/matugen/issues/237
# [templates.foot]
# input_path = '~/.config/matugen/templates/foot.ini'
# output_path = '~/.config/foot/colors.ini'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.astal]
input_path = '~/.config/matugen/templates/astal.scss'
output_path = '~/.config/astal-widgets/colors.scss'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-dark'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.qt6ct]
input_path = '~/.config/matugen/templates/qtct.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.qt5ct]
input_path = '~/.config/matugen/templates/qtct.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

# TODO: add neovim template
# [templates.nvim]
# input_path = '~/.config/nvim/pywal/matugen.lua'
# output_path = '~/.cache/wal/base46-dark.lua'
#
# [templates.nvimlight]
# input_path = '~/.config/nvim/pywal/matugen.lua'
# output_path = '~/.cache/wal/base46-light.lua'

[config.custom_colors]
base_0 = { color = "#100F0F", blend = false }
base_1 = { color = "#D14D41", blend = false }
base_2 = { color = "#879A39", blend = false }
base_3 = { color = "#CE5D97", blend = false }
base_4 = { color = "#4385BE", blend = false }
base_5 = { color = "#D0A215", blend = false }
base_6 = { color = "#3AA99F", blend = false }
base_7 = { color = "#CECDC3", blend = false }
base_8 = { color = "#403E3C", blend = false }
base_9 = { color = "#AF3029", blend = false }
base_10 = { color = "#66800B", blend = false }
base_11 = { color = "#A02F6F", blend = false }
base_12 = { color = "#205EA6", blend = false }
base_13 = { color = "#AD8301", blend = false }
base_14 = { color = "#24837B", blend = false }
base_15 = { color = "#FFFCF0", blend = false }
