[config]
set = false # this prevents setting wallpaper with matugen

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel.ini'
output_path = '~/.config/fuzzel/colors.ini'

[templates.foot]
input_path = '~/.config/matugen/templates/foot.ini'
output_path = '~/.config/foot/colors.ini'
