# common
bind = $mainMod, C, exec, uwsm app -- $terminal
bind = $mainMod SHIFT, C, exec, uwsm app -- $colorPicker
bind = $mainMod, E, exec, uwsm app -- $fileManager

# fuzzel
bind = $mainMod, space, exec, uwsm app -- $appLauncher
bind = $mainMod, Y, exec, uwsm app -- uuctl $appLauncher
bind = SUPER, V, exec, uwsm app -- bash $CUSTOM_SCRIPTS_DIR/cliphist-fuzzel-with-images.bash
bind = $mainMod, period, exec, uwsm app -- $emoji_picker

# hyprshot
bind = $mainMod, S, exec, uwsm app -- $screenshot_region
bind = $mainMod SHIFT, S, exec, uwsm app -- $screenshot_window
bind = $mainMod LEFT_CONTROL, S, exec, uwsm app -- $screenshot_monitor
