# common
bind = $mainMod, C, exec, uwsm app -- $terminal
bind = $mainMod SHIFT, C, exec, uwsm app -- $colorPicker
bind = $mainMod, E, exec, uwsm app -- $fileManager

# fuzzel
bind = $mainMod, space, global, caelestia:launcher
bind = $mainMod, Y, exec, uwsm app -- uuctl $appLauncher
bind = $mainMod, V, exec, uwsm app -- bash $clipboard_history
bind = $mainMod, period, exec, uwsm app -- $emoji_picker

# hyprshot
bind = $mainMod, S, global, caelestia:screenshotFreeze
bind = $mainMod SHIFT, S, exec, caelestia screenshot
