###################
### KEYBINDINGS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/
# Sets "Windows" key as main modifier
$mainMod = SUPER

binds {
  scroll_event_delay = false
}

source = ./apps.conf
source = ./window-manager.conf
source = ./system.conf
