# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  spinner:
    frames:
      - ''
      - ''
      - ''
      - ''
      - ''
      - ''
os:
  editPreset: 'nvim'
git:
  autoFetch: true
