source = ./colors.conf
source = ./hyprland-configs/monitors.conf
source = ./hyprland-configs/programs.conf
source = ./hyprland-configs/autostart-and-envs.conf
source = ./hyprland-configs/look-and-feel.conf
source = ./hyprland-configs/input.conf
source = ./hyprland-configs/keybinds/init.conf
source = ./hyprland-configs/rules.conf

xwayland {
  force_zero_scaling = true
}

debug {
    full_cm_proto = 1
}
