general {
  # when "loginctl lock-session" is called
  # start hyprlock if not already started
  lock_cmd = pidof hyprlock || hyprlock
  # when hyprlock is active
  on_lock_cmd = canberra-gtk-play -i service-logout;

  # when "loginctl unlock-session" is called
  # end hyprlock
  unlock_cmd = killall hyprlock
  # when hyprlock is not active
  on_unlock_cmd = canberra-gtk-play -i service-login;

  # lock session and stop astal@*
  before_sleep_cmd = loginctl lock-session; systemctl --user stop astal@*
  # turn on display and start astal@*
  after_sleep_cmd = hyprctl dispatch dpms on; systemctl --user start astal@* --all
}

# turn off screen when session is locked
listener {
  timeout = 15
  # turns off the screen if hyprlock is active
  on-timeout = pidof hyprlock && hyprctl dispatch dpms off && systemctl --user stop astal@*
  # command to run when activity is detected after timeout has fired.
  on-resume = pidof hyprlock && hyprctl dispatch dpms on && systemctl --user start astal@* --all
}

# screenlock
listener {
  # 10 min
  timeout = 600
  on-timeout = loginctl lock-session
}

# suspend
listener {
  # 15 min
  timeout = 900
  on-timeout = systemctl suspend
}
