# BACKGROUND
background {
    monitor =
    path = ~/Pictures/wallpapers/gravity.jpg
    blur_passes = 0
    # contrast = 0.8916
    # brightness = 0.5
    # vibrancy = 0.1696
    # vibrancy_darkness = 1
}

# GENERAL
general {
    ignore_empty_input = true
    hide_cursor = true
}


# ====== RIGHT BOX ======
# Day
label {
    text = cmd[update:1000] date +'%d %A' | tr '[:lower:]' '[:upper:]'
    color = rgb(878580)
    font_size = 20
    font_family = JetBrainsMono Nerd Font Thin
    text_align = right
    position = -20, 110
    halign = right
    valign = bottom
}

# Date-Month
label {
    text = cmd[update:1000] date +'%B' | tr '[:lower:]' '[:upper:]'
    color = rgb(878580)
    font_size = 20
    font_family = JetBrainsMono Nerd Font Thin
    text_align = right
    position = -20, 140
    halign = right
    valign = bottom
}

# Time
label {
    text = cmd[update:1000] echo $TIME
    color = rgb(CECDC3)
    font_size = 70
    font_family = JetBrainsMono Nerd Font Thin
    text_align = right
    position = -20, 10
    halign = right
    valign = bottom
}

# ====== LEFT BOX ======
# media: title
label {
    text = cmd[update:1000] astal-mpris info | jq -r '.[0].metadata."xesam:title"? | select(. != null)'
    color = rgb(CECDC3)
    font_size = 20
    font_family = JetBrainsMono Nerd Font Thin
    text_align = left
    position = 20, -10
    halign = left
    valign = top
}

# media: artist
label {
    text = cmd[update:1000] astal-mpris info | jq -r '.[0].metadata."xesam:artist".[0]? | select(. != null)'
    color = rgb(878580)
    font_size = 14
    font_family = JetBrainsMono Nerd Font Thin
    text_align = left
    position = 20, -44
    halign = left
    valign = top
}

# media: no playing text
label {
    text = cmd[update:1000] astal-mpris info | jq -r 'if (. | length) > 0 then empty else "no media playing ^.^" end'
    color = rgb(878580)
    font_size = 14
    font_family = JetBrainsMono Nerd Font Thin
    text_align = left
    position = 20, -44
    halign = left
    valign = top
}

# INPUT FIELD
input-field {

    size = 400, 60
    outline_thickness = 1
    rounding = 0
    # outer_color = rgba(255,255,255,1)
    outer_color = rgba(0,0,0,0)
    inner_color = rgba(0,0,0,0)

    swap_font_color = true
    font_color = rgb(CECDC3)
    check_color = rgb(878580)
    fail_color = rgb(D14D41)
    dots_text_format = <span> </span>
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    dots_rounding = 0

    fade_on_empty = false
    hide_input = false
    position = 0, 10
    halign = center
    valign = bottom

    font_family = JetBrainsMono Nerd Font
    placeholder_text = <span> type password </span>
    fail_text = <span> fail to unlock </span>
}
