source = ./hyprland-configs/monitors.conf
source = ./hyprland-configs/programs.conf
source = ./hyprland-configs/autostart.conf
source = ./hyprland-configs/look-and-feel.conf
source = ./hyprland-configs/input.conf
source = ./hyprland-configs/keybinds.conf
source = ./hyprland-configs/window-and-workspaces.conf

xwayland {
  force_zero_scaling = true
}

debug {
    full_cm_proto = 1
}
