#################
### AUTOSTART ###
#################

# workaround for gtk4 bug with cursor size
execr-once = gsettings set org.gnome.desktop.interface cursor-size 32

execr-once = uwsm app -- easyeffects --gapplication-service
execr-once = uwsm app -- bitwarden-desktop
execr-once = ./.config/hypr/checkupdates.fish

#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/

env = XCURSOR_SIZE,32
env = XCURSOR_THEME,Colloid-dark-cursors
env = TERMINAL,$terminal
env = QT_QPA_PLATFORMTHEME,qt6ct #theme for Qt apps
env = GTK_USE_PORTAL, 0
env = ELECTRON_OZONE_PLATFORM_HINT, wayland #force electron apps to use wayland
