#################
### AUTOSTART ###
#################

# workaround for gtk4 bug with cursor size
execr-once = gsettings set org.gnome.desktop.interface cursor-size 32

execr-once = uwsm app -- easyeffects --gapplication-service
execr-once = uwsm app -- bitwarden-desktop
execr-once = bash $CUSTOM_SCRIPTS_DIR/checkupdates.bash

#############################
### ENVIRONMENT VARIABLES ###
#############################

# other Environment-variables are in uwsm/env

# See https://wiki.hyprland.org/Configuring/Environment-variables/
env = TERMINAL,$terminal
