#################
### AUTOSTART ###
#################

# workaround for gtk4 bug with cursor size
execr-once = gsettings set org.gnome.desktop.interface cursor-size 32

execr-once = uwsm app -- easyeffects --gapplication-service
execr-once = uwsm app -- check-updates

# cliphist
execr-once = uwsm app -- wl-paste --type text --watch cliphist store
execr-once = uwsm app -- wl-paste --type image --watch cliphist store
execr-once = sleep 3 && canberra-gtk-play -i desktop-login

#############################
### ENVIRONMENT VARIABLES ###
#############################

# other Environment-variables are in uwsm/env

# See https://wiki.hyprland.org/Configuring/Environment-variables/
env = TERMINAL,$terminal
