################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor= , preferred, auto, 1
monitorv2 {
  output = desc:Zoran Corporation ZORAN HDMI TV 0x00000001
  mode = preferred
  position = auto
  scale = 1
}
monitorv2 {
  output = desc: Nreal MGMG2710C
  mode = 1920x1080@120.00Hz
  position = auto
  scale = 1
}
monitorv2 {
  output = desc: Samsung Electric Company LF24T450F HCPX700137
  mode = 1920x1080@60.00Hz
  position = auto-right
  scale = 1
}
