###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = foot
$fileManager = thunar
$appLauncher = fuzzel
$colorPicker = hyprpicker -a -n
$screenshot = hyprshot --clipboard-only
$screenshot-region = $screenshot -m region
$screenshot-window = $screenshot -m window
$screenshot-monitor = $screenshot -m output -m active
$change_zoom = $BASH_CONFIG_DIR/scripts/change-zoom.bash
$change_volume = $BASH_CONFIG_DIR/scripts/change-volume.bash
