###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = foot
$fileManager = thunar
$appLauncher = fuzzel
$colorPicker = hyprpicker -a -n
$screenshot = $CUSTOM_SCRIPTS_DIR/screenshot.bash
$screenshot_region = $screenshot region
$screenshot_window = $screenshot window
$screenshot_monitor = $screenshot output -m active
$change_zoom = $CUSTOM_SCRIPTS_DIR/change-zoom.bash
$change_volume = $CUSTOM_SCRIPTS_DIR/change-volume.bash
