##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

windowrule = noblur, class:^steam$, initialClass:^steam$
# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*
# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# checkupdates
windowrule = workspace special:magic, initialTitle:^System Update$, initialClass:^foot$
windowrule = pseudo                 , initialTitle:^System Update$, initialClass:^foot$
windowrule = size 1064 902          , initialTitle:^System Update$, initialClass:^foot$

# postman save file
windowrule = float,initialClass:^postman$, initialTitle:^Select path to save file$
windowrule = size 900 600,initialClass:^postman$, initialTitle:^Select path to save file$

# signal open file
windowrule = float,initialClass:^signal-desktop$, initialTitle:^Open Files$
windowrule = size 900 600,initialClass:^signal-desktop$, initialTitle:^Open Files$

# slack open file
windowrule = float,initialClass:^slack$, initialTitle:^Open Files$
windowrule = size 900 600,initialClass:^slack$, initialTitle:^Open Files$

# bitwarden
windowrule = noblur, initialClass:^Bitwarden$, initialTitle:^Bitwarden$

# thunar rename
windowrule = float, initialClass:thunar, initialTitle:^Rename \".+\"$
windowrule = size 500 200, initialClass:thunar, initialTitle:^Rename \".+\"$

# game rules
windowrule = monitor HDMI-A-1,class:^steam_app_\d+$
windowrule = workspace 5,class:^steam_app_\d+$
windowrule = content game, class:^steam_app_\d+$
windowrule = noblur, class:^steam_app_\d+$
windowrule = opaque, class:^steam_app_\d+$

windowrule = monitor HDMI-A-1, class:gamescope
windowrule = workspace 5, class:gamescope
windowrule = content game, class:gamescope
windowrule = noblur, class:gamescope
windowrule = opaque, class:gamescope

# workspace for games
workspace = 5, monitor:HDMI-A-1, border:false, rounding:false, decorate:false, shadow:false, persistent:false

# regular workspaces
workspace = 1,  monitor:HDMI-A-1, default:true, persistent:true
workspace = 2,  monitor:HDMI-A-1, persistent:true
workspace = 3,  monitor:HDMI-A-1, persistent:true
workspace = 4,  monitor:HDMI-A-1, persistent:true
workspace = 7,  monitor:DVI-D-1,  default:true, persistent:true
workspace = 8,  monitor:DVI-D-1,  persistent:true
workspace = 9,  monitor:DVI-D-1,  persistent:true
workspace = 10, monitor:DVI-D-1,  persistent:true
