##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

windowrule = noblur, class:^steam$, initialClass:^steam$
# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*
# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

windowrule = pseudo,initialClass:^foot$
windowrule = size 1000x900,initialClass:^foot$

# game rules
windowrule = monitor HDMI-A-1,class:^steam_app_\d+$
windowrule = workspace 10,class:^steam_app_\d+$
windowrule = content game, class:^steam_app_\d+$
windowrule = noblur, class:^steam_app_\d+$
windowrule = opaque, class:^steam_app_\d+$

windowrule = monitor HDMI-A-1, class:gamescope
windowrule = workspace 10, class:gamescope
windowrule = content game, class:gamescope
windowrule = noblur, class:gamescope
windowrule = opaque, class:gamescope

workspace = 10, border:false, rounding:false, decorate:false, monitor:HDMI-A-1, persistent:false
