[colors]
background={{colors.background.default.hex_stripped}}
foreground={{colors.on_background.default.hex_stripped}}

# BLACK
regular0={{colors.surface_container.default.hex_stripped}}
# RED
regular1={{colors.base_1.default.hex_stripped}}
# GREEN
regular2={{colors.base_2.default.hex_stripped}}
# MAGENTA
regular3={{colors.base_3.default.hex_stripped}}
# BLUE
regular4={{colors.base_4.default.hex_stripped}}
# YELLOW
regular5={{colors.base_5.default.hex_stripped}}
# CYAN
regular6={{colors.base_6.default.hex_stripped}}
# WHITE
regular7={{colors.base_7.default.hex_stripped}}

# BRIGTH BLACK
bright0={{colors.surface_container_highest.default.hex_stripped}}
# BRIGTH RED
bright1={{colors.base_9.default.hex_stripped}}
# BRIGTH GREEN
bright2={{colors.base_10.default.hex_stripped}}
# BRIGTH MAGENTA
bright3={{colors.base_11.default.hex_stripped}}
# BRIGTH BLUE
bright4={{colors.base_12.default.hex_stripped}}
# BRIGTH YELLOW
bright5={{colors.base_13.default.hex_stripped}}
# BRIGTH CYAN
bright6={{colors.base_14.default.hex_stripped}}
# BRIGTH WHITE
bright7={{colors.base_15.default.hex_stripped}}

# other stuff
scrollback-indicator={{colors.surface_container.default.hex_stripped}} {{colors.primary.default.hex_stripped}}
