[colors]
alpha=0.90
background={{colors.background.default.hex_stripped}}
foreground={{colors.on_surface.default.hex_stripped}}

# BLACK
regular0={{colors.surface_container_high.default.hex_stripped | auto_lightness: 10.0 }}
# RED
regular1={{colors.error.default.hex_stripped | auto_lightness: 20.0}}
# GREEN
regular2={{colors.primary.default.hex_stripped | auto_lightness: 10.0}}
# MAGENTA
regular3={{colors.primary.default.hex_stripped | invert | auto_lightness: 20.0}}
# BLUE
regular4={{colors.secondary.default.hex_stripped}}
# YELLOW
regular5={{colors.tertiary.default.hex_stripped}}
# CYAN
regular6={{colors.error.default.hex_stripped | auto_lightness: 20.0 | invert}}
# WHITE
regular7={{colors.inverse_surface.default.hex_stripped}}

# BRIGHT BLACK
bright0={{colors.surface_container_highest.default.hex_stripped | auto_lightness: 10.0 }}
# BRIGHT RED
bright1={{colors.error.default.hex_stripped}}
# BRIGHT GREEN
bright2={{colors.primary.default.hex_stripped | auto_lightness: -10.0}}
# BRIGHT MAGENTA
bright3={{colors.primary.default.hex_stripped | invert | auto_lightness: 30.0}}
# BRIGHT BLUE
bright4={{colors.secondary.default.hex_stripped | auto_lightness: -10.0}}
# BRIGHT YELLOW
bright5={{colors.tertiary.default.hex_stripped | auto_lightness: -10.0}}
# BRIGHT CYAN
bright6={{colors.error.default.hex_stripped | invert | auto_lightness: 30.0 }}
# BRIGHT WHITE
bright7={{colors.inverse_surface.default.hex_stripped}}
