[colors]
alpha=0.95
background={{colors.background.default.hex_stripped}}
foreground={{colors.on_background.default.hex_stripped}}

# BLACK
regular0={{colors.surface_container.default.hex_stripped}}
# RED
regular1={{colors.red.default.hex_stripped | auto_lightness: 20.0}}
# GREEN
regular2={{colors.green.default.hex_stripped | auto_lightness: 10.0}}
# MAGENTA
regular3={{colors.magenta.default.hex_stripped | auto_lightness: 20.0}}
# BLUE
regular4={{colors.blue.default.hex_stripped | auto_lightness: 20.0}}
# YELLOW
regular5={{colors.yellow.default.hex_stripped | auto_lightness: 10.0}}
# CYAN
regular6={{colors.cyan.default.hex_stripped | auto_lightness: 20.0}}
# WHITE
regular7={{colors.white.default.hex_stripped | auto_lightness: 20.0}}

# BRIGTH BLACK
bright0={{colors.surface_container_high.default.hex_stripped}}
# BRIGTH RED
bright1={{colors.red.default.hex_stripped | auto_lightness: 10.0}}
# BRIGTH GREEN
bright2={{colors.green.default.hex_stripped}}
# BRIGTH MAGENTA
bright3={{colors.magenta.default.hex_stripped | auto_lightness: 10.0}}
# BRIGTH BLUE
bright4={{colors.blue.default.hex_stripped | auto_lightness: 10.0}}
# BRIGTH YELLOW
bright5={{colors.yellow.default.hex_stripped}}
# BRIGTH CYAN
bright6={{colors.cyan.default.hex_stripped | auto_lightness: 10.0}}
# BRIGTH WHITE
bright7={{colors.white.default.hex_stripped | auto_lightness: 10.0}}

