alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias l1='ls -1'
alias ll='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias la1='ls -a1'
alias astal-config='cd /home/francisco/.config/astal-widgets/ && nvim'
alias nvim-config='cd ~/.config/nvim/lua/ && nvim'
alias fastfetch-config='cd ~/.config/fastfetch/ && nvim config.jsonc'
alias foot-config='cd ~/.config/foot/ && nvim foot.ini'
alias starship-config='cd ~/.config/ && nvim starship.toml'
alias hypr-config='cd ~/.config/hypr/ && nvim'
alias fuzzel-config='cd ~/.config/fuzzel/ && nvim fuzzel.ini'
alias ls-tree='tree --dirsfirst ./'
alias bash-config='cd ~/.config/bash/ && nvim'
alias systemd-config='cd ~/.config/systemd/user/ && nvim'
alias matugen-config='cd ~/.config/matugen && nvim'
alias sunsetr-config='cd ~/.config/sunsetr/ && nvim sunsetr.toml'
alias make-qr='qrtool encode -m 1 -t unicode'
alias uwsm-config='cd ~/.config/uwsm/ && nvim env'
alias pls='sudo'
