alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias l1='ls -1'
alias ll='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias la1='ls -a1'
alias ls-tree='tree --dirsfirst ./'
alias make-qr='qrtool encode -m 1 -t unicode'
alias pls='sudo'
