# -*- conf -*-
# config template: https://codeberg.org/dnkl/foot/src/branch/master/foot.ini
# config manual: https://man.archlinux.org/man/foot.ini.5.en

term=xterm-256color

font=JetBrainsMono Nerd Font:size=14:weight=light, Noto Color Emoji:size=14
horizontal-letter-offset=0
vertical-letter-offset=0
box-drawings-uses-font-glyphs=no
dpi-aware=yes

# initial-window-size-pixels=500x500
pad=0x7 center       # optionally append 'center'

[mouse]
hide-when-typing=yes

[cursor]
blink=yes

# flexoki
[colors]
alpha=1.0
background=100F0F
foreground=CECDC3
regular0=1C1B1A  # black
regular1=AF3029  # red
regular2=66800B  # green
regular3=AD8301  # yellow
regular4=205EA6  # blue
regular5=5E409D  # purple
regular6=24837B  # cyan
regular7=E6E4D9  # white

bright0=6F6E69 # bright black
bright1=D14D41 # bright red
bright2=879A39 # bright green
bright3=D0A215 # bright yellow
bright4=4385BE # bright blue
bright5=8B7EC8 # bright purple
bright6=3AA99F # bright cyan
bright7=FFFCF0 # bright white


[key-bindings]
spawn-terminal=none
scrollback-up-page=Mod1+Shift+u
scrollback-down-page=Mod1+Shift+d
scrollback-up-line=Mod1+Shift+k
scrollback-down-line=Mod1+Shift+j

[search-bindings]
find-prev=Control+p
find-next=Control+n

[url-bindings]
cancel=Control+g Control+c Control+d Escape
toggle-url-visible=t

# vim: ft=dosini
