# -*- conf -*-
# config template: https://codeberg.org/dnkl/foot/src/branch/master/foot.ini
# config manual: https://man.archlinux.org/man/foot.ini.5.en

term=xterm-256color

font=GoMono Nerd Font:size=13
horizontal-letter-offset=0
vertical-letter-offset=0
box-drawings-uses-font-glyphs=no
dpi-aware=yes

initial-window-size-pixels=900x900  # Or,
pad=0x0 center       # optionally append 'center'

[url]
launch=xdg-open ${url}
label-letters=sadfjklewcmpgh
osc8-underline=url-mode
protocols=http, https, ftp, ftps, file, gemini, gopher
uri-characters=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_.,~:;/?#@!$&%*+="'()[]


[mouse]
hide-when-typing=yes

# Rose-Piné Dawn (By cement-drinker)
[cursor]
color=faf4ed 575279

[colors]
# alpha=1.0
background=faf4ed
foreground=575279
regular0=f2e9e1	  # black (Overlay)
regular1=b4637a	  # red (Love)
regular2=31748f   # green (Pine)
regular3=ea9d34   # yellow (Gold)
regular4=56949f	   # blue (Foam)
regular5=907aa9	  # magenta (Iris)
regular6=d7827e	   # cyan (Rose)
regular7=575279   # white (Text)

bright0=9893a5	   # bright black (Muted)
bright1=b4637a	  # bright red (Love)
bright2=31748f   # bright green (Pine)
bright3=ea9d34   # bright yellow (Gold)
bright4=56949f	   # bright blue (Foam)
bright5=907aa9	  # bright magenta (Iris)
bright6=d7827e	   # bright cyan (Rose)
bright7=575279   # bright white (Text)

[key-bindings]
spawn-terminal=none

[url-bindings]
cancel=Control+g Control+c Control+d Escape
toggle-url-visible=t

# vim: ft=dosini
